// This file was generated by the storyblok CLI.
// DO NOT MODIFY THIS FILE BY HAND.
export interface CallToAction {
  title?: string;
  href?: string;
  component: "callToAction";
  _uid: string;
  [k: string]: unknown;
}

export interface Feature {
  name?: string;
  component: "feature";
  _uid: string;
  [k: string]: unknown;
}

export interface Footer {
  footerItem?: (CallToAction | Feature | Footer | GlobalBlogs | Grid | Header | NavItem | Page | Teaser)[];
  component: "footer";
  _uid: string;
  [k: string]: unknown;
}

export interface GlobalBlogs {
  footer?: unknown[];
  header?: Header[];
  component: "global-blogs";
  _uid: string;
  [k: string]: unknown;
}

export interface Grid {
  columns?: (CallToAction | Feature | Footer | GlobalBlogs | Grid | Header | NavItem | Page | Teaser)[];
  component: "grid";
  _uid: string;
  [k: string]: unknown;
}

export interface Header {
  logo?: string;
  items?: NavItem[];
  callToAction?: CallToAction[];
  component: "header";
  _uid: string;
  [k: string]: unknown;
}

export interface NavItem {
  title?: string;
  href?: string;
  component: "nav-item";
  _uid: string;
  [k: string]: unknown;
}

export interface Page {
  body?: (CallToAction | Feature | Footer | GlobalBlogs | Grid | Header | NavItem | Page | Teaser)[];
  component: "page";
  _uid: string;
  [k: string]: unknown;
}

export interface Teaser {
  headline?: string;
  component: "teaser";
  _uid: string;
  [k: string]: unknown;
}
