// This file was generated by the storyblok CLI.
// DO NOT MODIFY THIS FILE BY HAND.
export interface Feature {
  name?: string;
  component: "feature";
  _uid: string;
  [k: string]: unknown;
}

export interface Footer {
  footerItem?: (Feature | Footer | GlobalBlogs | Grid | Header | HeaderItem | Page | Teaser)[];
  component: "footer";
  _uid: string;
  [k: string]: unknown;
}

export interface GlobalBlogs {
  footer?: unknown[];
  header?: Header[];
  component: "global-blogs";
  _uid: string;
  [k: string]: unknown;
}

export interface Grid {
  columns?: (Feature | Footer | GlobalBlogs | Grid | Header | HeaderItem | Page | Teaser)[];
  component: "grid";
  _uid: string;
  [k: string]: unknown;
}

export interface Header {
  logo?: string;
  items?: HeaderItem[];
  component: "header";
  _uid: string;
  [k: string]: unknown;
}

export interface HeaderItem {
  title?: string;
  component: "header-item";
  _uid: string;
  [k: string]: unknown;
}

export interface Page {
  body?: (Feature | Footer | GlobalBlogs | Grid | Header | HeaderItem | Page | Teaser)[];
  component: "page";
  _uid: string;
  [k: string]: unknown;
}

export interface Teaser {
  headline?: string;
  component: "teaser";
  _uid: string;
  [k: string]: unknown;
}
