// This file was generated by the storyblok CLI.
// DO NOT MODIFY THIS FILE BY HAND.
import type { StoryblokMultiasset, StoryblokAsset } from '../storyblok.d.ts';
export interface AboutSection {
  image?: StoryblokAsset;
  eyebrow?: string;
  headingLine1?: string;
  headingEmphasis?: string;
  paragraph1?: string;
  paragraph2?: string;
  paragraph3?: string;
  stats?: AboutStat[];
  component: "aboutSection";
  _uid: string;
  [k: string]: unknown;
}

export interface AboutStat {
  value?: string;
  label?: string;
  component: "aboutStat";
  _uid: string;
  [k: string]: unknown;
}

export interface BeforeAfterSection {
  eyebrow?: string;
  subheading?: string;
  beforeImage?: StoryblokAsset;
  afterImage?: StoryblokAsset;
  beforeAlt?: string;
  afterAlt?: string;
  beforeLabel?: string;
  afterLabel?: string;
  component: "beforeAfterSection";
  _uid: string;
  [k: string]: unknown;
}

export interface CallToAction {
  title?: string;
  href?: string;
  variant?: "" | "primary" | "secondary";
  component: "callToAction";
  _uid: string;
  [k: string]: unknown;
}

export interface ContactSection {
  eyebrow?: string;
  headingLine1?: string;
  headingEmphasis?: string;
  headingLine2?: string;
  description?: string;
  emailLabel?: string;
  email?: string;
  phoneLabel?: string;
  phone?: string;
  studioLabel?: string;
  studio?: string;
  submitLabel?: string;
  component: "contactSection";
  _uid: string;
  [k: string]: unknown;
}

export interface Feature {
  name?: string;
  component: "feature";
  _uid: string;
  [k: string]: unknown;
}

export interface FinalCtaSection {
  headingLine1?: string;
  headingEmphasis?: string;
  description?: string;
  buttonLabel?: string;
  buttonHref?: string;
  component: "finalCtaSection";
  _uid: string;
  [k: string]: unknown;
}

export interface Footer {
  brandPrefix?: string;
  brandAccent?: string;
  description?: string;
  navigationHeading?: string;
  footerItem?: NavItem[];
  connectHeading?: string;
  email?: string;
  phone?: string;
  location?: string;
  instagramHref?: string;
  pinterestHref?: string;
  copyrightText?: string;
  craftedText?: string;
  component: "footer";
  _uid: string;
  [k: string]: unknown;
}

export interface GlobalBlogs {
  footer?: unknown[];
  header?: Header[];
  component: "global-blogs";
  _uid: string;
  [k: string]: unknown;
}

export interface Grid {
  columns?: (
    | AboutSection
    | AboutStat
    | BeforeAfterSection
    | CallToAction
    | ContactSection
    | Feature
    | FinalCtaSection
    | Footer
    | GlobalBlogs
    | Grid
    | Header
    | HeroSection
    | InstagramSection
    | NavItem
    | Page
    | ProcessSection
    | ProcessStep
    | ProjectCard
    | ProjectsSection
    | ServiceItem
    | Services
    | Teaser
  )[];
  component: "grid";
  _uid: string;
  [k: string]: unknown;
}

export interface Header {
  logo?: string;
  items?: NavItem[];
  callToAction?: CallToAction[];
  component: "header";
  _uid: string;
  [k: string]: unknown;
}

export interface HeroSection {
  bussinesTypeTitle?: string;
  headingFirstLine?: string;
  keyword?: string;
  headingSecondLine?: string;
  subHeading?: string;
  callToAction?: CallToAction[];
  viewProjectAction?: CallToAction[];
  image?: StoryblokAsset;
  component: "heroSection";
  _uid: string;
  [k: string]: unknown;
}

export interface InstagramSection {
  handle?: string;
  heading?: string;
  images?: StoryblokMultiasset;
  component: "instagramSection";
  _uid: string;
  [k: string]: unknown;
}

export interface NavItem {
  title?: string;
  href?: string;
  component: "nav-item";
  _uid: string;
  [k: string]: unknown;
}

export interface Page {
  body?: (
    | AboutSection
    | AboutStat
    | BeforeAfterSection
    | CallToAction
    | ContactSection
    | Feature
    | FinalCtaSection
    | Footer
    | GlobalBlogs
    | Grid
    | Header
    | HeroSection
    | InstagramSection
    | NavItem
    | Page
    | ProcessSection
    | ProcessStep
    | ProjectCard
    | ProjectsSection
    | ServiceItem
    | Services
    | Teaser
  )[];
  component: "page";
  _uid: string;
  [k: string]: unknown;
}

export interface ProcessSection {
  heading?: string;
  subheading?: string;
  steps?: ProcessStep[];
  component: "processSection";
  _uid: string;
  [k: string]: unknown;
}

export interface ProcessStep {
  num?: string;
  title?: string;
  desc?: string;
  component: "processStep";
  _uid: string;
  [k: string]: unknown;
}

export interface ProjectCard {
  img?: StoryblokAsset;
  title?: string;
  category?: "" | "Residential" | "Commercial";
  desc?: string;
  component: "projectCard";
  _uid: string;
  [k: string]: unknown;
}

export interface ProjectsSection {
  heading?: string;
  subheading?: string;
  projects?: ProjectCard[];
  component: "projectsSection";
  _uid: string;
  [k: string]: unknown;
}

export interface ServiceItem {
  title?: string;
  description?: string;
  icon?: unknown;
  component: "serviceItem";
  _uid: string;
  [k: string]: unknown;
}

export interface Services {
  heading?: string;
  subheading?: string;
  service?: ServiceItem[];
  component: "services";
  _uid: string;
  [k: string]: unknown;
}

export interface Teaser {
  headline?: string;
  component: "teaser";
  _uid: string;
  [k: string]: unknown;
}

export type ContentType = Page;
